import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { TRPCProvider } from "@/lib/trpc/provider";
import { AuthProvider } from "@/lib/auth/auth-provider";
import { CartBookmarkProvider } from "@/lib/auth/cart-bookmark-provider";
import {
  getUser,
  getUserCart,
  getUserBookmarks,
} from "@/server/auth/server-auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Theme script that runs BEFORE any content renders
// This prevents theme flash by setting the class on HTML element immediately
const themeScript = `
  (function() {
    function setTheme() {
      try {
        var theme = localStorage.getItem('app-theme');
        var isDark = theme === 'dark' || (!theme && window.matchMedia('(prefers-color-scheme: dark)').matches);
        if (isDark) {
          document.documentElement.classList.add('dark');
        } else {
          document.documentElement.classList.remove('dark');
        }
      } catch (e) {}
    }
    setTheme();
    // Also listen for system preference changes
    window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', setTheme);
  })();
`;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch user and their cart/bookmarks on the server before rendering
  const { user, newAccessToken } = await getUser();

  // Only fetch cart and bookmarks for logged-in users on server
  // Guest users will load cart from localStorage on client
  let initialCart: {
    productId: string;
    name: string;
    price: number;
    image?: string;
    quantity: number;
  }[] = [];
  let initialBookmarks: {
    productId: string;
    name: string;
    price: number;
    image?: string;
    addedAt: number;
  }[] = [];

  if (user) {
    initialCart = await getUserCart(user.id);
    initialBookmarks = await getUserBookmarks(user.id);
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TRPCProvider>
          <ThemeProvider defaultTheme="system">
            <AuthProvider initialUser={user} newAccessToken={newAccessToken}>
              <CartBookmarkProvider
                initialCart={initialCart}
                initialBookmarks={initialBookmarks}
              >
                <Toaster />
                {children}
              </CartBookmarkProvider>
            </AuthProvider>
          </ThemeProvider>
        </TRPCProvider>
      </body>
    </html>
  );
}
